version: '3.8'

services:
  # The main application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      # Uncomment the following line to use PostgreSQL
      # - DATABASE_URL=postgresql://postgres:postgres@db:5432/expense_tracker
    depends_on:
      # Uncomment the following line to use PostgreSQL
      # - db
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped

  # PostgreSQL database - uncomment to use
  # db:
  #   image: postgres:15-alpine
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=expense_tracker
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# Uncomment to use PostgreSQL
# volumes:
#   postgres_data: